name: Build
on:
  push:
    branches:

jobs:
  check-sass:
    name: Check that Sass has been run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install dependencies
        run: |
          npm install
          npm install -g sass

      - name: Run Sass
        run: grunt sass:dev

      - name: Check that the working directly is clean (no outstanding scss changes)
        run: git diff

  nix-build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v14.1
      - uses: cachix/cachix-action@v10
        with:
          name: autophagy
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build docs.nix

  nix-build:
    name: Nix build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v14.1
      - uses: cachix/cachix-action@v10
        with:
          name: autophagy
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build
